[project]
name = "kedantic"
version = "0.1.0"
description = "Plugin to allow Pydantic Models as Node Inputs in Kedro"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["kedro>=1.1.1", "pydantic>=2.12.5"]

[project.entry-points."kedro.hooks"]
kedantic = "kedantic.plugin:hooks"
